AWSTemplateFormatVersion: '2010-09-09'
Description: 'An example template with an IAM role for a Lambda state machine.'
Parameters:
  env:
    Type: String
  functionsfnListPatientIdName:
    Type: String
  functionsfnListPatientIdArn:
    Type: String
  functionsfnSumPatientActivitiesSumOnePatientName:
    Type: String
  functionsfnSumPatientActivitiesSumOnePatientArn:
    Type: String
Conditions:
  ShouldNotCreateEnvResources:
    Fn::Equals:
      - Ref: env
      - NONE
Resources:
  StatesExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - SumPatientActivitiesStatesExecutionRole
          - Fn::Join: ['', [SumPatientActivitiesStatesExecutionRole, '-', Ref: env]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - Fn::Sub: 'states.${AWS::Region}.amazonaws.com'
            Action: 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: '*'
              - Effect: Allow
                Action: 'states:*'
                Resource: '*'
  SumPatientActivitiesStepStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName:
        Fn::If:
          - ShouldNotCreateEnvResources
          - sumPatientActivitiesStep
          - Fn::Join: ['', [sumPatientActivitiesStep, '-', Ref: env]]
      DefinitionString:
        Fn::Sub:
          - |-
            {
              "Comment": "手動で実行する場合は、startDateとendDateを入力してください。(どちらも'YYYY-MM-DD')",
              "StartAt": "ListPatientId",
              "States": {
                "ListPatientId": {
                  "Type": "Task",
                  "Resource": "${functionsfnListPatientIdArn}",
                  "ResultPath": "$.patientIdList",
                  "Next": "SumAllPatients"
                },
                "SumAllPatients": {
                  "Type": "Map",
                  "ItemsPath": "$.patientIdList",
                  "Parameters": {
                    "patientId.$": "$$.Map.Item.Value.patientId",
                    "startDate.$": "$.startDate",
                    "endDate.$": "$.endDate"
                  },
                  "Iterator": {
                    "StartAt": "SumOnePatient",
                    "States": {
                      "SumOnePatient": {
                        "Type": "Task",
                        "Resource": "${functionsfnSumPatientActivitiesSumOnePatientArn}",
                        "End": true
                      }
                    }
                  },
                  "End": true
                }
              }
            }
          - functionsfnListPatientIdArn: { Ref: functionsfnListPatientIdArn }
            functionsfnSumPatientActivitiesSumOnePatientArn: { Ref: functionsfnSumPatientActivitiesSumOnePatientArn }
      RoleArn:
        Fn::GetAtt:
          - StatesExecutionRole
          - Arn
  SumPatientActivitiesStepTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Join: ['', [sumPatientActivitiesStepTopic, '-', Ref: env]]
  SumPatientActivitiesStepFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Join: ['', [SumPatientActivitiesStep-Failed-Alarm, '-', Ref: env]]
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - Ref: SumPatientActivitiesStepTopic
      InsufficientDataActions: []
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Statistic: Sum
      Dimensions:
        - Name: StateMachineArn
          Value:
            Ref: SumPatientActivitiesStepStateMachine
      Period: 3600
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
  SumPatientActivitiesStepTimedOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
        Fn::Join: ['', [SumPatientActivitiesStep-TimedOut-Alarm, '-', Ref: env]]
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - Ref: SumPatientActivitiesStepTopic
      InsufficientDataActions: []
      MetricName: ExecutionsTimedOut
      Namespace: AWS/States
      Statistic: Sum
      Dimensions:
        - Name: StateMachineArn
          Value:
            Ref: SumPatientActivitiesStepStateMachine
      Period: 3600
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing

Outputs:
  Arn:
    Value:
      Ref: SumPatientActivitiesStepStateMachine
  Region:
    Value:
      Ref: "AWS::Region"
  RoleName:
    Value:
      Ref: StatesExecutionRole
